env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode10.1
      script:
        - set -o pipefail
        - xcodebuild -scheme "Expression (Mac)" -sdk macosx clean build test
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t f835f552-0734-4266-b5c6-0c184c368bd9
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test
